CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Usuarios" (
    "Secuencial" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Correo" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Secuencial")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260731102658_InicialUsuarios', '8.0.10');

COMMIT;

