// <auto-generated />
using System;
using Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.ColumnaDb", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Secuencial"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("EstaActivo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("Orden");

                    b.Property<int>("SecuencialProyecto")
                        .HasColumnType("integer")
                        .HasColumnName("SecuencialProyecto");

                    b.HasKey("Secuencial");

                    b.HasIndex("SecuencialProyecto");

                    b.ToTable("Columnas", (string)null);
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.EstadoProyectoDb", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("EstaActivo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Codigo");

                    b.ToTable("EstadosProyecto", (string)null);
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.PrioridadDb", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("EstaActivo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Secuencial");

                    b.ToTable("Prioridades", (string)null);
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.ProyectoDb", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("CodigoEstadoProyecto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CodigoEstadoProyecto");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Secuencial");

                    b.HasIndex("CodigoEstadoProyecto");

                    b.ToTable("Proyectos", (string)null);
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.Proyecto_UsuarioDb", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Secuencial"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("EstaActivo");

                    b.Property<int>("SecuencialProyecto")
                        .HasColumnType("integer")
                        .HasColumnName("SecuencialProyecto");

                    b.Property<int>("SecuencialUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("SecuencialUsuario");

                    b.HasKey("Secuencial");

                    b.HasIndex("SecuencialProyecto");

                    b.HasIndex("SecuencialUsuario");

                    b.ToTable("Proyecto_Usuario", (string)null);
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.TareaDb", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("EstaActivo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("Orden");

                    b.Property<int>("SecuencialColumna")
                        .HasColumnType("integer")
                        .HasColumnName("SecuencialColumna");

                    b.Property<int>("SecuencialPrioridad")
                        .HasColumnType("integer")
                        .HasColumnName("SecuencialPrioridad");

                    b.Property<int>("SecuencialUsuarioAsignado")
                        .HasColumnType("integer")
                        .HasColumnName("SecuencialUsuarioAsignado");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Titulo");

                    b.HasKey("Secuencial");

                    b.HasIndex("SecuencialColumna");

                    b.HasIndex("SecuencialPrioridad");

                    b.HasIndex("SecuencialUsuarioAsignado");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.UsuarioDb", b =>
                {
                    b.Property<int>("Secuencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Secuencial"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.HasKey("Secuencial");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.ColumnaDb", b =>
                {
                    b.HasOne("Api.Infrastructure.Persistence.Entities.ProyectoDb", "Proyecto")
                        .WithMany()
                        .HasForeignKey("SecuencialProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.ProyectoDb", b =>
                {
                    b.HasOne("Api.Infrastructure.Persistence.Entities.EstadoProyectoDb", "EstadoProyecto")
                        .WithMany()
                        .HasForeignKey("CodigoEstadoProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoProyecto");
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.Proyecto_UsuarioDb", b =>
                {
                    b.HasOne("Api.Infrastructure.Persistence.Entities.ProyectoDb", "Proyecto")
                        .WithMany()
                        .HasForeignKey("SecuencialProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Infrastructure.Persistence.Entities.UsuarioDb", "Usuario")
                        .WithMany()
                        .HasForeignKey("SecuencialUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Api.Infrastructure.Persistence.Entities.TareaDb", b =>
                {
                    b.HasOne("Api.Infrastructure.Persistence.Entities.ColumnaDb", "Columna")
                        .WithMany()
                        .HasForeignKey("SecuencialColumna")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Infrastructure.Persistence.Entities.PrioridadDb", "Prioridad")
                        .WithMany()
                        .HasForeignKey("SecuencialPrioridad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Infrastructure.Persistence.Entities.UsuarioDb", "UsuarioAsignado")
                        .WithMany()
                        .HasForeignKey("SecuencialUsuarioAsignado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Columna");

                    b.Navigation("Prioridad");

                    b.Navigation("UsuarioAsignado");
                });
#pragma warning restore 612, 618
        }
    }
}
